---
# This file is managed centrally by modulesync
#   https://github.com/theforeman/foreman-installer-modulesync
rvm:
  - 2.1.9
  - 2.3.0
  - 2.4.1
env:
  matrix:
    - PUPPET_VERSION=4.9
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.1
      env: PUPPET_VERSION=5.0
    - rvm: 2.5.1
      env: PUPPET_VERSION=5.0
bundler_args: --without system_tests development
sudo: false
